"""
ai_filter.py — Gemini AI-powered signal filter.

Before a signal is published to Telegram, this module sends the full
technical setup to Gemini 2.0 Flash for review. Gemini acts as an
expert crypto trader who can:
  - APPROVE the signal (optionally adjusting confidence)
  - REJECT the signal (with reasoning)

Falls back gracefully: if the API is unavailable, the signal passes through
unmodified (fail-open design).
"""
import json
import time
from typing import Optional

from config.settings import (
    GEMINI_API_KEY, AI_FILTER_ENABLED, AI_MODEL,
)
from config.logger import get_logger

logger = get_logger(__name__)

# Cache recent AI decisions to avoid re-reviewing the same setup
_review_cache: dict = {}
CACHE_TTL = 300  # 5 minutes


SYSTEM_PROMPT = """You are an expert cryptocurrency trader with 15 years of experience in technical analysis. You review trading signals generated by a rule-based scanner before they are published.

Your job is to act as a quality gate — approve strong setups and reject weak ones.

DECISION RULES:
1. APPROVE signals with strong indicator confluence (3+ confirming indicators)
2. REJECT signals where indicators conflict or the setup is weak
3. REJECT signals on low-liquidity or stablecoin-like pairs
4. Be MORE cautious with SHORT signals (crypto has a long bias)
5. Adjust confidence UP for exceptional setups (strong trend + volume + multiple confirmations)
6. Adjust confidence DOWN for marginal setups (mixed signals, low volume, choppy market)

CRITICAL FILTERS — ALWAYS REJECT:
- RSI in neutral zone (40-60) with no other strong confirmation
- MACD histogram near zero with no clear crossover
- Choppy market regime with ADX < 20
- Price within 0.5% of a strong S/R level going against the trade
- Volume ratio below 1.0 (below average volume)

You MUST respond with valid JSON only. No markdown, no explanation outside the JSON."""


REVIEW_SCHEMA = {
    "type": "object",
    "properties": {
        "action": {
            "type": "string",
            "enum": ["APPROVE", "REJECT"],
            "description": "Whether to approve or reject this signal"
        },
        "adjusted_confidence": {
            "type": "integer",
            "description": "Adjusted confidence score (50-100). Only meaningful if action is APPROVE."
        },
        "reasoning": {
            "type": "string",
            "description": "Brief 1-2 sentence explanation of the decision"
        },
        "risk_notes": {
            "type": "string",
            "description": "Key risk to watch for this trade (1 sentence)"
        }
    },
    "required": ["action", "adjusted_confidence", "reasoning", "risk_notes"]
}


def _build_review_prompt(
    score_result: dict,
    symbol: str,
    exchange: str,
    style: str,
    market_type: str,
    sentiment: Optional[dict] = None,
) -> str:
    """Build the prompt with all indicator data for Gemini to review."""
    ind = score_result.get("indicators", {})
    direction = score_result.get("direction", "?")
    confidence = score_result.get("confidence", 0)
    reasons = score_result.get("reasons", [])

    # Format indicator values
    rsi = ind.get("rsi")
    macd_hist = ind.get("macd_hist")
    adx = ind.get("adx")
    atr_pct = ind.get("atr_pct")
    vol_ratio = ind.get("vol_ratio")
    regime = ind.get("market_regime", "unknown")

    prompt = f"""Review this {style.upper()} trading signal:

SIGNAL: {symbol} {direction} on {exchange.upper()} ({market_type})
RULE-BASED CONFIDENCE: {confidence}%
TRIGGERED REASONS: {', '.join(reasons) if reasons else 'None'}

INDICATORS:
- RSI: {f'{rsi:.1f}' if rsi else 'N/A'}
- MACD Histogram: {f'{macd_hist:.6f}' if macd_hist else 'N/A'}
- MACD Cross: {'Bullish' if ind.get('macd_cross_bull') else 'Bearish' if ind.get('macd_cross_bear') else 'None'}
- EMA Alignment: {'9>21>50 Bull' if ind.get('ema_bull') else '9<21<50 Bear' if ind.get('ema_bear') else 'Mixed'}
- Above EMA200: {ind.get('above_200', 'N/A')}
- ADX: {f'{adx:.0f}' if adx else 'N/A'} ({'Trending' if ind.get('trending') else 'Weak'})
- ATR%: {f'{atr_pct:.2f}%' if atr_pct else 'N/A'}
- Volume Ratio: {f'{vol_ratio:.1f}x' if vol_ratio else 'N/A'} ({'SPIKE' if ind.get('vol_spike') else 'normal'})
- Stochastic K: {f'{ind.get("stoch_k", 0):.1f}' if ind.get('stoch_k') else 'N/A'}
- OBV: {'Rising' if ind.get('obv_rising') is True else 'Falling' if ind.get('obv_rising') is False else 'N/A'}
- Above VWAP: {ind.get('above_vwap', 'N/A')}
- BB Squeeze: {ind.get('bb_squeeze', False)}

MARKET CONTEXT:
- Regime: {regime}
- Price Structure: {'Bullish (HH+HL)' if ind.get('structure_bull') else 'Bearish (LH+LL)' if ind.get('structure_bear') else 'No clear structure'}
- Nearest Resistance: {f'${ind.get("nearest_resistance")}' if ind.get('nearest_resistance') else 'None detected'}
- Nearest Support: {f'${ind.get("nearest_support")}' if ind.get('nearest_support') else 'None detected'}"""

    if sentiment:
        prompt += f"""

MARKET SENTIMENT:
- Fear & Greed Index: {sentiment.get('value', 'N/A')} ({sentiment.get('label', 'N/A')})"""

    prompt += """

Should this signal be APPROVED or REJECTED? Respond with JSON only."""

    return prompt


async def review_signal(
    score_result: dict,
    symbol: str,
    exchange: str,
    style: str,
    market_type: str,
    sentiment: Optional[dict] = None,
) -> dict:
    """
    Send a signal to Gemini for AI review.

    Returns:
        {
            "action": "APPROVE" | "REJECT",
            "adjusted_confidence": int,
            "reasoning": str,
            "risk_notes": str,
        }

    Falls back to APPROVE with original confidence if AI is disabled or fails.
    """
    original_conf = score_result.get("confidence", 0)
    fallback = {
        "action": "APPROVE",
        "adjusted_confidence": original_conf,
        "reasoning": "AI filter bypassed",
        "risk_notes": "",
    }

    if not AI_FILTER_ENABLED or not GEMINI_API_KEY:
        return fallback

    # Check cache
    cache_key = f"{symbol}:{score_result.get('direction')}:{style}:{exchange}"
    now = time.time()
    if cache_key in _review_cache:
        cached_time, cached_result = _review_cache[cache_key]
        if now - cached_time < CACHE_TTL:
            logger.debug(f"AI cache hit for {cache_key}")
            return cached_result

    try:
        from google import genai
        from google.genai import types

        client = genai.Client(api_key=GEMINI_API_KEY)

        prompt = _build_review_prompt(
            score_result, symbol, exchange, style, market_type, sentiment
        )

        response = client.models.generate_content(
            model=AI_MODEL,
            contents=prompt,
            config=types.GenerateContentConfig(
                system_instruction=SYSTEM_PROMPT,
                temperature=0.1,
                response_mime_type="application/json",
                response_schema=REVIEW_SCHEMA,
            ),
        )

        result_text = response.text.strip()
        result = json.loads(result_text)

        # Validate and sanitize
        action = result.get("action", "APPROVE")
        if action not in ("APPROVE", "REJECT"):
            action = "APPROVE"

        adj_conf = result.get("adjusted_confidence", original_conf)
        adj_conf = max(50, min(100, int(adj_conf)))

        review = {
            "action": action,
            "adjusted_confidence": adj_conf,
            "reasoning": result.get("reasoning", ""),
            "risk_notes": result.get("risk_notes", ""),
        }

        # Cache result
        _review_cache[cache_key] = (now, review)

        # Clean old cache entries
        expired = [k for k, (t, _) in _review_cache.items() if now - t > CACHE_TTL]
        for k in expired:
            del _review_cache[k]

        log_msg = (f"AI {action}: {symbol} {score_result.get('direction')} "
                   f"conf {original_conf}→{adj_conf} | {review['reasoning']}")
        if action == "APPROVE":
            logger.info(log_msg)
        else:
            logger.info(log_msg)

        return review

    except Exception as e:
        logger.warning(f"AI filter error: {e} — signal passes through unmodified")
        return fallback
